site_name: Computational Biology Core - Brown University
site_author: Ashok Ragavendran
repo_url: https://github.com/compbiocore/bioflows
site_description: Documentation for running Bioinformatics/Computational workflows with bioflowa
site_url: https://compbiocore.github.io/
google_analytics: [ 'UA-115983496-2', 'compbiocore.github.io' ]

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  logo: assets/cbc-logo.svg

extra_css:
  - styles/dark_mode.css
  - docs/assets/adm.css
  - https://use.fontawesome.com/releases/v5.8.0/css/all.css
markdown_extensions:
  - extra
  - tables
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - Docs: intro.md
  - Command Options: command_description.md
  - Tutorials:
      - Download All genomes: tutorials/download_all.md
      - Download a specific list of Genomes: tutorials/download_list.md
      - Exclude one genome from a set: tutorials/exclude_one.md