# This is a basic workflow to help you get started with Actions

name: Buid and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - Name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      # Runs a set of commands using the runners shell
      - Name: Setup Mkdocs
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: foo
      - Name: Bash
        shell: bash -l {0}
        run: |
          conda info
          conda list 
          conda install python=3
          conda install pip
          which pip
          pip install mkdocs
          pip install mkdocs-material
          mkdocs -h
          mkdir -p docs/styles
          mkdir -p docs/assets
          mkdir -p mkdocs_build
          curl https://gist.githubusercontent.com/fernandogelin/08ecff3387dffc374c4abf06a577ab71/raw/29ad95fcc771ce49ff6cecc56346218a0e929df8/dark_mode.css > docs/styles/dark_mode.css
          curl https://gist.githubusercontent.com/fernandogelin/b02ee98f2f35ce4263093f7a1c66582b/raw/20ca5a37eb6defe00d35e50e7e00a784b64309f9/cbc-logo.svg > docs/assets/cbc-logo.svg
          mkdocs build -d mkdocs_build --verbose --clean --strict
      - Name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
         #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages # The branch the action should deploy to.
         FOLDER: mkdocs_build # The folder the action should deploy.
         CLEAN: true # Automatically remove deleted files from the deploy branch
